name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:
    if: >-
      !startsWith(github.event.commits[0].message, 'Update to r')
      || github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with: { node-version: ">=26", check-latest: true }
    - uses: ZhongRuoyu/setup-llvm@v0
      with: { llvm-version: "22" }
    - run: pwsh -f build.ps1
