name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ZhongRuoyu/setup-llvm@v0
        with: { llvm-version: "22" }
      - run: pwsh -f build.ps1
